language: python

python:
  - "2.7"
  - "3.6"

env:
  global:
    - NUODB_HOME=/opt/nuodb
    - TZ=America/New_York
    - NUO_ADD_DOMAIN_PASS=yes
    - NUO_START_AGENT=yes
  matrix:
    - NUO_VERSION=3.1.2.1
    - NUO_VERSION=3.2.0.2

notifications:
  recipients:
    - drivers@nuodb.com
    - psmith@nuodb.com

before_install:
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/enabled >/dev/null
  - echo madvise | sudo tee /sys/kernel/mm/transparent_hugepage/defrag >/dev/null

  # There's a bug in the Trusty images where this gives a syntax error
  # See https://github.com/travis-ci/travis-ci/issues/8906
  - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp

  - wget -q "http://download.nuohub.org/nuodb-ce_${NUO_VERSION}_amd64.deb" --output-document=/var/tmp/nuodb.deb
  - sudo dpkg -i /var/tmp/nuodb.deb

install:
  - make install

before_script:
  - if [ "$NUO_ADD_DOMAIN_PASS" = yes ]; then printf '\ndomainPassword = bird\n' | sudo tee -a "$NUODB_HOME"/etc/default.properties >/dev/null; fi
  - if [ "$NUO_START_AGENT" = yes ]; then sudo service nuoagent start; fi

script:
  - make test

after_failure:
  - cat "$NUODB_HOME"/etc/default.properties
  - cat /var/log/nuodb/agent.log
